config_version = "0"

[plugins.definitions.markdownlint]
exported_config_paths = ["markdown/.markdownlint.json"]

[plugins.definitions.yamllint]
exported_config_paths = ["yaml/.yamllint.yaml"]

[plugins.definitions.shellcheck]
exported_config_paths = ["shell/.shellcheckrc"]
